# Generated by Django 5.2.4 on 2026-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examassignment_admin_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrouppermission',
            name='duration',
            field=models.IntegerField(blank=True, help_text="Guruh uchun test davomiyligi. Bo'sh bo'lsa imtihon davomiyligi ishlatiladi.", null=True, verbose_name='Vaqt (daqiqa)'),
        ),
    ]
