# Generated by Django 6.0.2 on 2026-03-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examgrouppermission_duration'),
        ('users', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.studentgroup', verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.subject', verbose_name='Fan'),
        ),
        migrations.AlterUniqueTogether(
            name='examassignment',
            unique_together={('subject', 'group', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='examassignment',
            name='exam',
        ),
    ]
