# Generated by Django 6.0.2 on 2026-03-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_restructure_exam_assignment'),
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.studentgroup', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.subject', verbose_name='Fan'),
        ),
    ]
