# Generated by Django 6.0.2 on 2026-03-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_examassignment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrouppermission',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt'),
        ),
        migrations.AddField(
            model_name='examgrouppermission',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('ended', 'Tugatilgan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat'),
        ),
    ]
